name: Algolia Search Index

on:
  workflow_dispatch:

jobs:
  build-algolia-search-index:
    name: Build Algolia Search Index
    runs-on: ubuntu-latest
    if: ${{ false }} # disabled until Algolia secrets are configured secrets.ALGOLIA_APP_ID && secrets.ALGOLIA_CRAWLER_API_KEY
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Crawler
      run: |
        docker run \
        -e APPLICATION_ID=${{ secrets.ALGOLIA_APP_ID }} \
        -e API_KEY=${{ secrets.ALGOLIA_CRAWLER_API_KEY }} \
        -e "CONFIG=$(cat ./docsearch.json | jq -r tostring)" \
        algolia/docsearch-scraper
